### ISSUE TITLE
Submit your request of homework_2 assignment selections.

### ISSUE THREAD

**Issue by shawnli2020** [shawnli2020/RaptorsSpringCamp#12]
Please see [wiki page](https://github.com/shawnli2020/RaptorsSpringCamp/wiki/Homework%232-Play-with-SimpleSimulator-and-Try-Simple-Changes) for detailed instructions. Leave a comment here if any questions.

The submit window is honored between 12pm April 8th and 12pm April 9th.

**Comment by WOLD-STUBBY** [comment]
can I request one now or do I have to wait for tomorrow?

**Comment by shawnli2020** [comment]
Hi Austin,

I appreciate if you could wait until tomorrow noon to submit. 

But please feel free to go through each assignment and even look into the code, try out the simulator notebook first. Luckily the 5 assignments this week are pretty much at same level of complexity.

Thanks,
Shawn

**Comment by WOLD-STUBBY** [comment]
This is Austin's list:
First choice: #5 
Second choice: #4

**Comment by shawnli2020** [comment]
Thanks Austin.

Could you please also submit your choices using the following procedure specified in the wiki page?

Thanks,
Shawn


---

* Synchronize your local git development branch to the remote master branch. From somewhere in your local jupyter work directory, issue the following git command from a shell terminal:
    > git pull rsc master
 
* Modify the rsc_hw_2_assignment_requests_and_grants.txt directly under the _**hw2**_ subfolder of the jupyter work directory, and copy the below template of "assignment selections" (also found in the txt file itself), and replace the appropriate fields with your own information:

> 
>RSC Homework #2 Assignment Selections by:
>
>[replace with your github username]
>
>[replace with your real-world name, first followed by last]
>
>[replace with the date of submitting this request]
>
>First Choice: 
>
>[replace with the title of your first choice assignment]
>
>Second Choice:
>
>[replace with the title of your second choice assignment]

* Stage and commit this modified file in your local username_dev branch, and push to your remote username_dev branch of this GitHub project of RaptorsSpringCamp.
>
> Again, stay with the following procedure:

    - work, stage, and commit on a local development branch
     
    - push the commits on local development branch to your own remote development branch
     
    - then request pull to master from there.

* Create and submit a git pull request for merge the modified txt file to the remote master branch of this project.
> 
    - this should be done in your web browser by navigating to your remote branch on GitHub project under "Code" tab.

**Comment by albertli2020** [comment]
What’s Austin’s email? Terri needs it.

**Comment by shawnli2020** [comment]
Hi Albert,

Let's not side-track from the homework assignments. You can search your gmail history to find Austin's email.

Thanks,
Shawn

**Comment by albertli2020** [comment]
Just tell Terri his email

**Comment by shawnli2020** [comment]
All assignments are granted/assigned:
----
1.Move the robot's start position. [to: Albert]
2. Change the robot's start orientation. [to: Baron. Assigned by default as the only choice left.]
3. Place the goal rectangle block at a different location in the robot's domain/world. [to: Claire]
4. Add walls to construct a maze-like challenge. [to: Hanlun]
5. Change to use a different set of keys to "user" control the robot. [to Austin, who requested in the issue page.]
